layout: "main"
logger: "console"
charset: "utf8"
appname: "Broadway"
route_cache: 0
template: "template_toolkit"
engines:
  template_toolkit:
    COMPILE_EXT: ".ttc" 
    COMPILE_DIR: "/tmp/ttcompile"

# broadway
broadway:
  title: "Version Control with Git"
  date: "Oct. 18, 2011"
  event: "Radford"
  author: "Dan Prince & Naveed Massjouni"
  slides: 29
  refresh_rate: 600
  remote: 1

